---
# vars file for mysql
# MYSQL_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/mrmotam/dev/mysql_password', decrypt=true, region='us-east-1') }}"
MYSQL_PASSWORD: "{{ lookup('amazon.aws.aws_ssm', '/mrmotam/dev/mysql_password', decrypt=False, region='us-east-1' ) }}"